#!/bin/bash

while getopts "h" arg; do
    case $arg in
        h)
            echo "Usage: dump_traffic [LPORT] [RHOST]"
            exit 1
            ;;
    esac
done    

sudo tcpdump -i enp0s31f6 -nn -vv -A tcp port $1 and dst $2 
