#!/bin/bash

wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=FILEID' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1LWeL5piT1qV8fNb9zASTq9Y5gRVeKS1B3ccKQ7cIURg" -O '904ehd-startingpoint.ovpn' && rm -rf /tmp/cookies.txt
